version: 1

ui:
  task_url_template: https://gitlab.com/oleg-shatov/hse-caos-public/-/tree/main/tasks/$GROUP_NAME/$TASK_NAME

  links:
    "TG Channel": https://t.me/+_jBGtnWAYrNmMjg6
    "TG Chat": https://t.me/+NwR0LdxxLckyMjli

deadlines:
  timezone: Europe/Moscow

  deadlines: interpolate  # hard/interpolate
  max_submissions: 100

  schedule:
    - group: 01-basic-io
      start: 2025-09-07 10:00
      steps:
        1.0: 2025-09-19 21:00
        0.5: 2025-09-26 21:00
      end: 2026-01-01 00:00
      enabled: true
      tasks:
        - task: a-plus-b
          score: 100
        - task: char-sum
          score: 100
        - task: reverse-list
          score: 100
        - task: fib-root
          score: 100
        - task: list
          score: 100

    - group: 02-files
      start: 2025-09-16 07:00
      steps:
        1.0: 2025-09-28 21:00
        0.5: 2025-10-05 21:00
      end: 2026-01-01 00:00
      enabled: true
      tasks:
        - task: buf-writer
          score: 100
        - task: simple-traverse
          score: 100
        - task: binary-tree
          score: 100
        - task: broken-symlinks
          score: 100
        - task: capture-output
          score: 100

    - group: 03-mmap
      start: 2025-09-23 19:00
      steps:
        1.0: 2025-10-05 21:00
        0.5: 2025-10-12 21:00
      end: 2026-01-01 00:00
      enabled: true
      tasks:
        - task: average
          score: 100
        - task: c-strings
          score: 100
        - task: binary-tree-2
          score: 100
        - task: spiral
          score: 100
        - task: simple-allocator
          score: 100

    - group: 04-procs-1
      start: 2025-09-01 13:00
      steps:
        1.0: 2025-10-13 21:00
        0.5: 2025-10-20 21:00
      end: 2026-01-01 00:00
      enabled: true
      tasks:
        - task: redirect-io
          score: 100
        - task: simple-pipeline
          score: 100
        - task: magic-ring-buffer
          score: 100
        - task: proc-reduce
          score: 100
        - task: allocator
          score: 100



grades:
  grades:
    10: [{ percent: 95 }]
    9: [{ percent: 85 }]
    8: [{ percent: 75 }]
    7: [{ percent: 65 }]
    6: [{ percent: 55 }]
    5: [{ percent: 45 }]
    4: [{ percent: 35 }]
    3: [{ percent: 25 }]
    2: [{ percent: 15 }]
    1: [{ percent: 5 }]
    0: [{ percent: 0 }]

