version: 1

ui:
  task_url_template: https://gitlab.com/oleg-shatov/hse-caos-public/-/tree/main/tasks/$GROUP_NAME/$TASK_NAME

  links:
    "TG Channel": https://t.me/+_jBGtnWAYrNmMjg6
    "TG Chat": https://t.me/+NwR0LdxxLckyMjli

deadlines:
  timezone: Europe/Moscow

  deadlines: interpolate  # hard/interpolate
  max_submissions: 100

  schedule:
    - group: 01-basic-io
      start: 2025-08-30 10:00
      steps:
        1.0: 2025-09-02 20:10
        0.5: 2025-09-03 20:00
      end: 2025-09-05 00:00
      enabled: true
      tasks:
        - task: a-plus-b
          score: 10
        - task: char-sum
          score: 10
        - task: list
          score: 100

grades:
  grades:
    10: [{ percent: 95 }]
    9: [{ percent: 85 }]
    8: [{ percent: 75 }]
    7: [{ percent: 65 }]
    6: [{ percent: 55 }]
    5: [{ percent: 45 }]
    4: [{ percent: 35 }]
    3: [{ percent: 25 }]
    2: [{ percent: 15 }]
    1: [{ percent: 5 }]
    0: [{ percent: 0 }]

