version: 1

ui:
  task_url_template: https://gitlab.com/oleg-shatov/hse-caos-public/-/tree/main/tasks/$GROUP_NAME/$TASK_NAME

  links:
    "TG Channel": https://t.me/+_jBGtnWAYrNmMjg6
    "TG Chat": https://t.me/+NwR0LdxxLckyMjli

deadlines:
  timezone: Europe/Moscow

  deadlines: interpolate  # hard/interpolate
  max_submissions: 100

  schedule:
    - group: 01-basic-io
      start: 2025-09-07 10:00
      steps:
        1.0: 2025-09-19 21:00
        0.5: 2025-09-26 21:00
      end: 2025-12-19 23:59
      enabled: true
      tasks:
        - task: a-plus-b
          score: 100
        - task: char-sum
          score: 100
        - task: reverse-list
          score: 100
        - task: fib-root
          score: 100
        - task: list
          score: 100

    - group: 02-files
      start: 2025-09-16 07:00
      steps:
        1.0: 2025-09-28 21:00
        0.5: 2025-10-05 21:00
      end: 2025-12-19 23:59
      enabled: true
      tasks:
        - task: buf-writer
          score: 100
        - task: simple-traverse
          score: 100
        - task: binary-tree
          score: 100
        - task: broken-symlinks
          score: 100
        - task: capture-output
          score: 100

    - group: 03-mmap
      start: 2025-09-23 19:00
      steps:
        1.0: 2025-10-05 21:00
        0.5: 2025-10-12 21:00
      end: 2025-12-19 23:59
      enabled: true
      tasks:
        - task: average
          score: 100
        - task: c-strings
          score: 100
        - task: binary-tree-2
          score: 100
        - task: spiral
          score: 100
        - task: simple-allocator
          score: 100

    - group: 04-procs-1
      start: 2025-10-01 13:00
      steps:
        1.0: 2025-10-13 21:00
        0.5: 2025-10-20 21:00
      end: 2025-12-19 23:59
      enabled: true
      tasks:
        - task: redirect-io
          score: 100
        - task: simple-pipeline
          score: 100
        - task: magic-ring-buffer
          score: 100
        - task: proc-reduce
          score: 100
        - task: allocator
          score: 100

    - group: 05-misc
      start: 2025-10-08 13:00
      steps:
        1.0: 2025-10-20 21:00
        0.5: 2025-10-27 21:00
      end: 2025-12-19 23:59
      enabled: true
      tasks:
        - task: goto
          score: 100
        - task: check-c
          score: 100
        - task: utf-wc
          score: 100
        - task: fork-timeout
          score: 100
        - task: execvpe
          score: 100

    - group: 06-asm-1
      start: 2025-10-15 13:00
      steps:
        1.0: 2025-11-03 21:00
        0.5: 2025-11-10 21:00
      end: 2025-12-19 23:59
      enabled: true
      tasks:
        - task: arg-sum-1
          score: 100
        - task: arg-sum-2
          score: 100
        - task: deref
          score: 100
        - task: tree-sum
          score: 100
        - task: persistent-stack
          score: 100

    - group: 07-asm-2
      start: 2025-10-23 21:00
      steps:
        1.0: 2025-11-13 21:00
        0.5: 2025-11-20 21:00
      end: 2025-12-19 23:59
      enabled: true
      tasks:
        - task: args-fwd
          score: 50
        - task: wrong-function-1
          score: 100
        - task: wrong-function-2
          score: 100
        - task: backtrace
          score: 100
        - task: pivot
          score: 150

    - group: 08-asm-3
      start: 2025-11-12 16:00
      steps:
        1.0: 2025-11-26 21:00
        0.5: 2025-12-02 21:00
      end: 2025-12-19 23:59
      enabled: true
      tasks:
        - task: dynlib
          score: 100
        - task: indirect-call
          score: 100
        - task: syscalls
          score: 100
        - task: print-args
          score: 100
        - task: polish-compiler
          score: 250

    - group: 09-fp-thr
      start: 2025-11-20 15:00
      steps:
        1.0: 2025-12-05 21:00
        0.5: 2025-12-11 21:00
      end: 2025-12-19 23:59
      enabled: true
      tasks:
        - task: mul8
          score: 100
        - task: atomic
          score: 100
        - task: philosophers
          score: 100
        - task: contract
          score: 100
        - task: queue
          score: 100

    - group: 10-thr
      start: 2025-12-04 09:00
      steps:
        1.0: 2025-12-17 21:00
        0.5: 2025-12-23 21:00
      end: 2025-12-23 21:01
      enabled: true
      tasks:
        - task: implication
          score: 100
        - task: computation
          score: 100
        - task: thread-local-alloc
          score: 100
        - task: limbo
          score: 100
        - task: rw-lock
          score: 100
        - task: rw-lock-starvation
          score: 100
          url: https://gitlab.com/oleg-shatov/hse-caos-public/-/tree/main/tasks/10-thr/rw-lock

    - group: 11-net-sig
      start: 2025-12-10 09:00
      steps:
        1.0: 2025-12-19 23:59
        0.5: 2025-12-24 21:00
      end: 2025-12-24 21:01
      enabled: true
      tasks:
        - task: addrinfo
          score: 100
        - task: ignore
          score: 100
        - task: logger
          score: 100
        - task: files
          score: 100
        - task: chat
          score: 100

    - group: bonus
      start: 2025-10-25 19:00
      end: 2025-12-31 18:00
      enabled: true
      tasks:
        - task: long-jump
          is_bonus: true
          score: 150
        - task: polish-compiler-tracing
          is_bonus: true
          score: 250
          url: https://gitlab.com/oleg-shatov/hse-caos-public/-/tree/main/tasks/08-asm-3/polish-compiler?ref_type=heads#%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5
        - task: coro
          is_bonus: true
          score: 250
        - task: interval
          is_bonus: true
          score: 100
        - task: backtrace-2
          is_bonus: true
          score: 150

grades:
  grades:
    10: [{ percent: 95 }]
    9: [{ percent: 85 }]
    8: [{ percent: 75 }]
    7: [{ percent: 65 }]
    6: [{ percent: 55 }]
    5: [{ percent: 45 }]
    4: [{ percent: 35 }]
    3: [{ percent: 25 }]
    2: [{ percent: 15 }]
    1: [{ percent: 5 }]
    0: [{ percent: 0 }]

