# DinD service is required for Testcontainers
services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ["--tls=false"]

variables:
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2


stages:
  - test
  - deploy

.base:
  image: rust:1.88
  timeout: 10m
  tags: ["kek-today"]
  variables:
    CARGO_HOME: "$CI_PROJECT_DIR/.cargo-home"
    CARGO_TARGET_DIR: "$CI_PROJECT_DIR/target"

test-solutions-clang:
  extends: .base
  stage: test
  script:
    - apt-get update && apt-get install -y cmake clang-19
    - CXX=$(which clang++-19) CC=$(which clang-19) ./common/tools/test_all_tasks.sh
  cache:
    - key: rust-build
      paths:
        - target/
        - .cargo-home/
        - Cargo.lock
    - key: clang-build
      paths:
        - build_*/


test-solutions-gcc:
  extends: .base
  stage: test
  script:
    - apt-get update && apt-get install -y cmake
    - CXX=$(which g++) CC=$(which gcc) ./common/tools/test_all_tasks.sh
  cache:
    - key: rust-build
      paths:
        - target/
        - .cargo-home/
        - Cargo.lock
    - key: gcc-build
      paths:
        - build_*/


check-rust-infra:
  extends: .base
  stage: test
  script:
    - rustup component add clippy
    - cargo check
    - cargo clippy
  cache:
    - key: rust-build
      paths:
        - target/
        - .cargo-home/
        - Cargo.lock

push-public:
  extends: .base
  stage: deploy
  # rules:
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  #     when: manual
  #   - when: never
  script:
    - apt-get update && apt-get install -y cmake
    - git config --global user.name "Oleg Shatov"
    - git config --global user.email "oleq.shatov@yandex.ru"
    - public_dir="$(mktemp -d)"
    - trap "rm -rf $public_dir" EXIT
    - echo "Using $public_dir for public repo"
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/oleg-shatov/hse-caos-public.git "$public_dir"
    - cargo xtask compose --in-path . --out-path "$public_dir" --skip .git --skip target --skip .cargo-home --stat
    - (cd $public_dir; ./common/tools/build_all_tasks.sh)
    - |
      (cd $public_dir &&
      git add --all &&
      git commit --allow-empty -m "Public files export" &&
      git push https://caos:${PUSH_TO_PUBLIC_TOKEN}@gitlab.com/oleg-shatov/hse-caos-public.git HEAD:main)
  cache:
    - key: rust-build
      paths:
        - target/
        - .cargo-home/
        - Cargo.lock

build-container:
  stage: deploy
  image: docker:dind
  needs: ['push-public']
  script:
    - docker login -u domwst -p ${DOCKER_PAT}
    - docker build . -t domwst/caos-runner
    - docker push domwst/caos-runner

