stages:
  - prepare
  - test
  - publish

.base:
  image: $CI_IMAGE_NAME
  timeout: 20m
  tags: [kek-today]
  variables:
    CACHE_DIR: /cache_cicd/$CI_PROJECT_PATH
    CARGO_HOME_BASE: $CACHE_DIR/cargo-home
    CARGO_HOME: "$CARGO_HOME_BASE"
    CARGO_TARGET_DIR_BASE: "$CACHE_DIR/target"
    CARGO_TARGET_DIR: "$CARGO_TARGET_DIR_BASE"
    GIT_STRATEGY: fetch
    GIT_DEPTH: 7

.dind-base:
  extends: .base
  image: docker:dind
  before_script:
    - docker login -u domwst -p ${DOCKER_PAT}
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

.test-base:
  extends: .base
  stage: test
  rules:
    - if: '$CI_COMMIT_TITLE =~ /^pub-ci-skip: /'
      when: never
    - when: on_success

build-ci-container:
  extends: .dind-base
  stage: prepare
  only:
    changes:
      - .private-ci/**
  script:
    - docker build .private-ci -t $CI_IMAGE_NAME
    - docker push $CI_IMAGE_NAME

test-solutions-clang:
  extends: .test-base
  variables:
    CARGO_HOME: "${CARGO_HOME_BASE}-clang"
    CARGO_TARGET_DIR: "${CARGO_TARGET_DIR_BASE}-clang"
  script:
    - CXX=$(which clang++-19) CC=$(which clang-19) ./common/tools/test_all_tasks.sh
  cache:
    - key: clang-build
      paths:
        - build_*/


test-solutions-gcc:
  extends: .test-base
  variables:
    CARGO_HOME: "${CARGO_HOME_BASE}-gcc"
    CARGO_TARGET_DIR: "${CARGO_TARGET_DIR_BASE}-gcc"
  script:
    - CXX=$(which g++) CC=$(which gcc) ./common/tools/test_all_tasks.sh
  cache:
    - key: gcc-build
      paths:
        - build_*/


check-rust-infra:
  extends: .test-base
  script:
    - rustup component add clippy rustfmt
    - cargo fmt --check
    - cargo check
    - cargo clippy

.clone-repo:
  variables:
    GIT_STRATEGY: clone

test-public-build:
  extends: [.test-base, .clone-repo]
  variables:
    CARGO_HOME: "${CARGO_HOME_BASE}-clang"
    CARGO_TARGET_DIR: "${CARGO_TARGET_DIR_BASE}-clang"
  cache:
    - key: test-public-build
      paths:
        - build_*/
  script:
    - git restore-mtime
    - git clone ${PUBLIC_REPO_PULL} public-repo
    - git -C public-repo restore-mtime
    - ./common/tools/export_to.sh public-repo --skip public-repo
    - mkdir -p build_{release,debug,asan,tsan}
    - |
      (cd public-repo;
      for i in ../build_*; do ln -s $i .; done;
      CXX=$(which clang++-19) CC=$(which clang-19) ./common/tools/build_all_tasks.sh &&
      echo "Public diff:" &&
      git add -N . &&
      git status &&
      git diff --color &&
      git diff --stat)

.publish-base:
  extends: .base
  stage: publish

push-public:
  extends: [.publish-base, .clone-repo]
  rules:
    - if: '$CI_COMMIT_TITLE =~ /^pub(-ci-skip)?: /'
      when: on_success
    - if: '$CI_COMMIT_TITLE =~ /^pub-manual: /'
      when: manual
      allow_failure: false
    - when: never
  script:
    - git config --global user.name "Oleg Shatov"
    - git config --global user.email "oleq.shatov@yandex.ru"
    - git clone --depth 2 ${PUBLIC_REPO_PULL} public-repo
    - >
      curl --fail --silent -X POST -H "Authorization: Bearer $MT_TESTER_TOKEN"
      -H "Content-type: application/x-yaml" --data-binary "@.manytask.yaml"
      "https://manytask.hse-caos.org/api/$MT_COURSE_NAME/update_config"
    - >
      curl --fail --silent -X POST -H "Authorization: Bearer $MT_TESTER_TOKEN"
      "https://manytask.hse-caos.org/api/$MT_COURSE_NAME/update_cache"
    - ./common/tools/export_to.sh public-repo --skip public-repo
    - |
      (cd public-repo &&
      git add . &&
      git commit --allow-empty -m "$(sed -E 's/^pub(-manual|-ci-skip)?: //' <<< "$CI_COMMIT_TITLE")" &&
      git push ${PUBLIC_REPO_PUSH} HEAD:main)

build-container:
  extends:
    - .publish-base
    - .dind-base
  rules:
    - if: '$CI_COMMIT_TITLE =~ /^pub(-manual|-ci-skip)?: /'
      when: on_success
    - when: never
  needs: ["push-public"]
  timeout: 1h
  script:
    - >
      docker build --build-arg CI_IMAGE_NAME=${CI_IMAGE_NAME}
      --build-arg PUBLIC_REPO=${PUBLIC_REPO_PULL} . -t $RUNNER_IMAGE_NAME
    - docker push $RUNNER_IMAGE_NAME
    - docker image prune -f --filter "until=5h"
    - docker system prune -f
