stages:
  - prepare
  - test
  - publish

.base:
  image: domwst/caos-private-ci
  timeout: 20m
  tags: [kek-today]
  variables:
    CACHE_DIR: /cache_cicd/$CI_PROJECT_PATH
    CARGO_HOME: $CACHE_DIR/.cargo-home
    CARGO_TARGET_DIR: "$CACHE_DIR/target"
    GIT_STRATEGY: fetch
    GIT_DEPTH: 7

.dind-base:
  extends: .base
  image: docker:dind
  before_script:
    - docker login -u domwst -p ${DOCKER_PAT}
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

build-ci-container:
  extends: .dind-base
  stage: prepare
  only:
    changes:
      - .private-ci/**
  script:
    - docker build .private-ci -t domwst/caos-private-ci
    - docker push domwst/caos-private-ci

test-solutions-clang:
  extends: .base
  stage: test
  script:
    - CXX=$(which clang++-19) CC=$(which clang-19) ./common/tools/test_all_tasks.sh
  cache:
    - key: clang-build
      paths:
        - build_*/


test-solutions-gcc:
  extends: .base
  stage: test
  script:
    - CXX=$(which g++) CC=$(which gcc) ./common/tools/test_all_tasks.sh
  cache:
    - key: gcc-build
      paths:
        - build_*/


check-rust-infra:
  extends: .base
  stage: test
  script:
    - cargo fmt --check
    - cargo check
    - cargo clippy

.clone-repo:
  variables:
    GIT_STRATEGY: clone

test-public-repo-build:
  stage: test
  extends: [.base, .clone-repo]
  script:
    - git clone https://gitlab.com/oleg-shatov/hse-caos-public.git public-repo
    - ./common/tools/export_to.sh public-repo --skip public-repo
    - |
      (cd public-repo;
      CXX=$(which clang++-19) CC=$(which clang-19) ./common/tools/build_all_tasks.sh &&
      echo "Public diff:" &&
      git add -N . &&
      git status &&
      git diff --color &&
      git diff --stat)

.publish-base:
  extends: .base
  stage: publish

push-public:
  extends: [.publish-base, .clone-repo]
  rules:
    - if: '$CI_COMMIT_TITLE =~ /^pub: /'
      when: on_success
    - if: '$CI_COMMIT_TITLE =~ /^pub-manual: /'
      when: manual
    - when: never
  script:
    - git config --global user.name "Oleg Shatov"
    - git config --global user.email "oleq.shatov@yandex.ru"
    - git clone --depth 2 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/oleg-shatov/hse-caos-public.git public-repo
    - ./common/tools/export_to.sh public-repo --skip public-repo
    - |
      (cd public-repo &&
      git add . &&
      git commit --allow-empty -m "$(sed -E 's/^pub(-manual)?: //' <<< "$CI_COMMIT_TITLE")" &&
      git push https://caos:${PUSH_TO_PUBLIC_TOKEN}@gitlab.com/oleg-shatov/hse-caos-public.git HEAD:main)
    - >
      curl --fail --silent -X POST -H "Authorization: Bearer $MT_TESTER_TOKEN"
      -H "Content-type: application/x-yaml" --data-binary "@.manytask.yaml"
      "https://manytask.kek.today/api/$MT_COURSE_NAME/update_config"
    - >
      curl --fail --silent -X POST -H "Authorization: Bearer $MT_TESTER_TOKEN"
      "https://manytask.kek.today/api/$MT_COURSE_NAME/update_cache"

build-container:
  extends:
    - .publish-base
    - .dind-base
  rules:
    - if: '$CI_COMMIT_TITLE =~ /^pub(-manual)?: /'
      when: on_success
    - when: never
  needs: ["push-public"]
  script:
    - docker build . -t domwst/caos-runner
    - docker push domwst/caos-runner

