stages:
  - prepare
  - test
  - publish

.base:
  image: domwst/caos-private-ci
  timeout: 20m
  tags: ["kek-today"]
  variables:
    CACHE_DIR: /cache_cicd/$CI_PROJECT_PATH
    CARGO_HOME: $CACHE_DIR/.cargo-home
    CARGO_TARGET_DIR: "$CACHE_DIR/target"

.dind-base:
  extends: .base
  image: docker:dind
  before_script:
    - docker login -u domwst -p ${DOCKER_PAT}
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

build-ci-container:
  extends: .dind-base
  stage: prepare
  only:
    changes:
      - .private-ci/**
  script:
    - docker build .private-ci -t domwst/caos-private-ci
    - docker push domwst/caos-private-ci

test-solutions-clang:
  extends: .base
  stage: test
  script:
    - CXX=$(which clang++-19) CC=$(which clang-19) ./common/tools/test_all_tasks.sh
  cache:
    - key: clang-build
      paths:
        - build_*/


test-solutions-gcc:
  extends: .base
  stage: test
  script:
    - CXX=$(which g++) CC=$(which gcc) ./common/tools/test_all_tasks.sh
  cache:
    - key: gcc-build
      paths:
        - build_*/


check-rust-infra:
  extends: .base
  stage: test
  script:
    - cargo check
    - cargo clippy

test-public-repo-build:
  stage: test
  extends: .base
  script:
    - public_dir="$(mktemp -d)"
    - trap "rm -rf $public_dir" EXIT
    - echo "Using $public_dir for public repo"
    - git clone https://gitlab.com/oleg-shatov/hse-caos-public.git "$public_dir"
    - ./common/tools/export_to.sh "$public_dir"
    - |
      (cd $public_dir;
      CXX=$(which clang++-19) CC=$(which clang-19) ./common/tools/build_all_tasks.sh &&
      echo "Public diff:" &&
      git add -N . &&
      git status &&
      git diff --stat &&
      git diff --color)

.publish-base:
  extends: .base
  stage: publish
  rules:
    - if: '$CI_COMMIT_TITLE =~ /^pub: /'
      when: on_success
    - when: never

push-public:
  extends: .publish-base
  script:
    - git config --global user.name "Oleg Shatov"
    - git config --global user.email "oleq.shatov@yandex.ru"
    - public_dir="$(mktemp -d)"
    - trap "rm -rf $public_dir" EXIT
    - echo "Using $public_dir for public repo"
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/oleg-shatov/hse-caos-public.git "$public_dir"
    - ./common/tools/export_to.sh "$public_dir"
    - |
      (cd $public_dir &&
      git add . &&
      git commit --allow-empty -m "${CI_COMMIT_TITLE#pub: }" &&
      git push https://caos:${PUSH_TO_PUBLIC_TOKEN}@gitlab.com/oleg-shatov/hse-caos-public.git HEAD:main)

build-container:
  extends:
    - .publish-base
    - .dind-base
  needs: ["push-public"]
  script:
    - docker build . -t domwst/caos-runner
    - docker push domwst/caos-runner

