stages:
  - test
  - publish

.base:
  image: rust:1.88
  timeout: 10m
  tags: ["kek-today"]
  variables:
    CACHE_DIR: /cache_cicd/$CI_PROJECT_PATH
    CARGO_HOME: $CACHE_DIR/.cargo-home
    CARGO_TARGET_DIR: "$CACHE_DIR/target"

test-solutions-clang:
  extends: .base
  stage: test
  script:
    - apt-get update && apt-get install -y cmake clang-19
    - CXX=$(which clang++-19) CC=$(which clang-19) ./common/tools/test_all_tasks.sh
  cache:
    - key: clang-build
      paths:
        - build_*/


test-solutions-gcc:
  extends: .base
  stage: test
  script:
    - apt-get update && apt-get install -y cmake
    - CXX=$(which g++) CC=$(which gcc) ./common/tools/test_all_tasks.sh
  cache:
    - key: gcc-build
      paths:
        - build_*/


check-rust-infra:
  extends: .base
  stage: test
  script:
    - rustup component add clippy
    - cargo check
    - cargo clippy

test-public-repo-build:
  stage: test
  extends: .base
  script:
    - apt-get update && apt-get install -y cmake
    - public_dir="$(mktemp -d)"
    - trap "rm -rf $public_dir" EXIT
    - echo "Using $public_dir for public repo"
    - git clone https://gitlab.com/oleg-shatov/hse-caos-public.git "$public_dir"
    - cargo xtask compose --in-path . --out-path "$public_dir" --skip .git --stat
    - |
      (cd $public_dir;
      ./common/tools/build_all_tasks.sh &&
      echo "Public diff:" &&
      git add -N . &&
      git status &&
      git diff --stat &&
      git diff --color)

.publish-base:
  extends: .base
  stage: publish
  rules:
    - if: '$CI_COMMIT_TITLE =~ /^pub: /'
      when: on_success
    - when: never

push-public:
  extends: .publish-base
  script:
    - git config --global user.name "Oleg Shatov"
    - git config --global user.email "oleq.shatov@yandex.ru"
    - public_dir="$(mktemp -d)"
    - trap "rm -rf $public_dir" EXIT
    - echo "Using $public_dir for public repo"
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/oleg-shatov/hse-caos-public.git "$public_dir"
    - cargo xtask compose --in-path . --out-path "$public_dir" --skip .git --skip target --skip .cargo-home --stat
    - |
      (cd $public_dir &&
      git add . &&
      git commit --allow-empty -m "Public files export" &&
      git push https://caos:${PUSH_TO_PUBLIC_TOKEN}@gitlab.com/oleg-shatov/hse-caos-public.git HEAD:main)

build-container:
  extends: .publish-base
  image: docker:dind
  needs: ["push-public"]
  script:
    - docker login -u domwst -p ${DOCKER_PAT}
    - docker build . -t domwst/caos-runner
    - docker push domwst/caos-runner
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

